[package]
name = "mdsite"
version = "0.1.5"
edition = "2024"
description = "Minimal static site generator from Markdown"
license = "APACHE-2.0"
readme = "README.md"

[dependencies]
clap = { version = "4", features = ["derive"] }
thiserror = "2"
walkdir = "2"
pulldown-cmark = { version = "0", default-features = false, features = [
    "html",
] }
unicode-width = "0"
syntect = { version = "5", default-features = false, features = [
    "default-fancy",
] }
toml = "0"
chrono = "0"

[dev-dependencies]
tempfile = "3"

[[bin]]
name = "mdsite"
path = "src/bin/mdsite.rs"
