[default]
domain = "example.com"
generate_sitemap = true
generate_llms = true
generate_rss = true
generate_robots = true

[llms]
prefix = """# Welcome to example.com.

The following links point to every page on the site in markdown format:

"""
